/**
 * mesh-rpc.mjs -- Phase 1 of the BrowserMeshFetch/BrowserMeshWebSocket plan
 * (`browsermesh-fetch-websocket.md`, a plan that runs in parallel with, and
 * is NOT part of, the CloudStorage mesh-native-services plan that phases
 * C-G of this package otherwise implement): the missing mesh-RPC transport
 * that `packages/browsermesh-discovery/src/sw-routing.mjs`'s `MeshFetchRouter`
 * has always expected to be handed as its `onRpc` callback
 * (`onRpc({podId, method, path, headers, body}) -> Promise<{status?, headers?,
 * body}>`) but that this repo never actually implemented. A LATER phase (2,
 * not this one) wires this file's `request()` into that `onRpc` slot; this
 * phase only builds the transport itself and does not import or touch
 * `sw-routing.mjs`.
 *
 * Built as a `MeshService` (Phase C, `mesh-service.mjs`), following
 * `chunk-replication.mjs`'s `queryHave()`/`fetchFrom()` request-with-timeout
 * pattern as the closest precedent: wire payloads travel over
 * `ctx.onIncomingData()`/`ctx.sendTo()`, filtered by `envelope.type` (default
 * `'mesh-rpc'`), on the same dispatch bus every other `MeshService` in this
 * family uses. Unlike `chunk-replication.mjs`, there is no fixed
 * resource/scope here -- this is a general-purpose request/response
 * envelope pair, not a chunk-store-specific protocol.
 *
 * ---------------------------------------------------------------------------
 * Wire protocol -- two message kinds sharing one envelope `type` (default
 * `'mesh-rpc'`):
 *
 *   Request (caller -> responder):
 *     `{ type, kind: 'rpc-request', requestId, method, path, headers, body }`
 *
 *   Response (responder -> caller), always sent back, even for an error:
 *     `{ type, kind: 'rpc-response', requestId, status, headers, body }`
 *
 * `requestId` is generated by the calling side (`nextRequestId()`, the same
 * `${podId}:${Date.now()}:${seq}` shape `chunk-replication.mjs` uses) and
 * echoed back verbatim by the responder, so multiple concurrent in-flight
 * `request()` calls -- to the same peer or different peers -- are correlated
 * independently via a `Map<requestId, {resolve, reject, timer}>` (see
 * `pendingRequests` below); there is no shared mutable "current request"
 * state anywhere in this file, so there is no crosstalk between concurrent
 * callers by construction.
 *
 * ---------------------------------------------------------------------------
 * AUTHORIZATION IS EXPLICITLY OUT OF SCOPE FOR THIS TRANSPORT (the plan's
 * own "Design decisions" section, restated here because it's easy to miss):
 * unlike `chunk-replication.mjs`/`manifest-sync.mjs`, this file does not
 * check `ctx.registry.checkAccess()` against any resource/scope, and does
 * not depend on `GrantLog` at all. A general-purpose RPC transport has no
 * fixed resource to check a scope against -- deciding what `{method, path}`
 * combinations are allowed for a given caller is the RESPONDING POD's own
 * `onRequest` handler's job, exactly the way a real HTTP server's
 * application code owns its own authorization, not its TCP/TLS transport
 * layer. Callers that need authorization should implement it inside the
 * `onRequest` handler they pass to `createMeshRpcService()`.
 *
 * ---------------------------------------------------------------------------
 * NO HANDLER REGISTERED -- if a pod attaches this service with no
 * `onRequest` (or attaches no `mesh-rpc` service at all), every inbound
 * request still gets a clean, explicit `501`-shaped response
 * (`{status: 501, body: {error: 'no RPC handler registered'}}`) rather than
 * being silently dropped (which would leave the caller's `request()`
 * waiting out the full timeout for no discoverable reason) or thrown
 * (which would crash the shared `ctx.onIncomingData()` dispatch loop every
 * other `MeshService` on this same `peerNode` also relies on).
 *
 * `onRequest` THROWING is handled the same defensive way: caught and turned
 * into a clean `{status: 500, body: {error: err.message}}` response sent
 * back to the caller, never an unhandled rejection and never a crash of the
 * dispatch loop (see `handleRequest()`'s `try/catch` below).
 *
 * ---------------------------------------------------------------------------
 * DEFAULT TIMEOUT: 10000ms (`DEFAULT_REQUEST_TIMEOUT_MS`). Chosen
 * deliberately longer than `chunk-replication.mjs`'s timeouts
 * (1.5-3s, tuned for one already-chunked, size-capped ciphertext blob over a
 * single WebRTC/loopback hop) because this transport's `{method, path,
 * headers, body}` shape is general-purpose -- a responding pod's own
 * `onRequest` handler might do real work (a local disk/IndexedDB read, a
 * nested mesh call of its own, etc.) before replying, and this file has no
 * way to know how expensive that handler is ahead of time. 10s is a
 * "generous enough that a legitimate slow handler doesn't get punished,
 * short enough that a caller relying on this for something interactive
 * (Phase 2's `browserMeshFetch()`) doesn't hang indefinitely" starting
 * default, not a tuned constant -- callers with different latency
 * expectations should override it via
 * `createMeshRpcService({ requestTimeoutMs })`.
 *
 * No browser-only imports at module level.
 */

/** Default `envelope.type` used to route mesh-RPC payloads on the shared `onIncomingData()` bus. */
const DEFAULT_ENVELOPE_TYPE = 'mesh-rpc'

/**
 * How long `request()` waits for a matching `rpc-response` envelope before
 * giving up and rejecting. See the module doc comment's "DEFAULT TIMEOUT"
 * section for the full reasoning -- this is a starting default, not a tuned
 * constant.
 */
const DEFAULT_REQUEST_TIMEOUT_MS = 10000

// ---------------------------------------------------------------------------
// createMeshRpcService
// ---------------------------------------------------------------------------

/**
 * Build a `MeshService` descriptor (`mesh-service.mjs`, Phase C) that
 * implements a general-purpose request/response RPC transport over
 * `ctx.sendTo()`/`ctx.onIncomingData()`, addressed directly by podId. See
 * this file's module doc comment for the full wire-protocol/authorization
 * writeup.
 *
 * @param {object} [opts]
 * @param {(req: {fromPubKey: string, method: string, path: string, headers: object, body: *}) => Promise<{status?: number, headers?: object, body?: *}>} [opts.onRequest]
 *   Optional. Called for every inbound RPC request this peer receives.
 *   If omitted, every inbound request gets a `501`-shaped response instead
 *   of being silently dropped -- see module doc comment. A thrown/rejected
 *   `onRequest` is caught and turned into a `500`-shaped response, never an
 *   unhandled rejection.
 * @param {string} [opts.envelopeType='mesh-rpc']
 * @param {number} [opts.requestTimeoutMs=10000] - See `DEFAULT_REQUEST_TIMEOUT_MS`'s doc comment.
 * @param {Function} [opts.onLog]
 * @returns {import('./mesh-service.mjs').MeshService}
 */
export function createMeshRpcService({
  onRequest,
  envelopeType = DEFAULT_ENVELOPE_TYPE,
  requestTimeoutMs = DEFAULT_REQUEST_TIMEOUT_MS,
  onLog,
} = {}) {
  if (onRequest !== undefined && typeof onRequest !== 'function') {
    throw new Error('createMeshRpcService: onRequest must be a function if provided')
  }

  const log = onLog || (() => {})

  return {
    name: 'mesh-rpc',

    attach(peerNode, ctx) {
      let reqSeq = 0
      /** Monotonic-ish unique id for correlating a request with its eventual response. */
      const nextRequestId = () => `${peerNode?.podId || 'local'}:${Date.now()}:${++reqSeq}`

      /**
       * @type {Map<string, {resolve: (res: {status: number, headers: object, body: *}) => void,
       *   reject: (err: Error) => void, timer: ReturnType<typeof setTimeout>}>}
       * requestId -> in-flight outbound request tracking, see `request()`.
       * Every entry is independent -- concurrent requests to the same or
       * different peers never share state, so there is no crosstalk by
       * construction.
       */
      const pendingRequests = new Map()

      // -----------------------------------------------------------------
      // Inbound dispatch
      // -----------------------------------------------------------------
      const unsubscribe = ctx.onIncomingData(envelopeType, (fromPubKey, msg) => {
        if (!msg || typeof msg.kind !== 'string') return
        if (msg.kind === 'rpc-request') {
          handleRequest(fromPubKey, msg).catch((err) => {
            // handleRequest() itself already catches onRequest()'s own
            // errors and turns them into a clean response -- reaching here
            // would mean sendTo() itself failed (e.g. the peer disconnected
            // mid-flight), which is logged, not rethrown, so it can never
            // crash the shared onIncomingData() dispatch loop.
            log('mesh-rpc:request-handling-failed', { from: fromPubKey, requestId: msg.requestId, error: err?.message || String(err) })
          })
        } else if (msg.kind === 'rpc-response') {
          handleResponse(fromPubKey, msg)
        }
      })

      // -----------------------------------------------------------------
      // Responding side -- this peer receiving an inbound RPC request.
      // -----------------------------------------------------------------

      /** @param {string} fromPubKey @param {object} msg */
      async function handleRequest(fromPubKey, msg) {
        const { requestId } = msg
        let result

        if (typeof onRequest !== 'function') {
          // No handler registered at all -- an explicit, discoverable
          // 501, never a silent drop (see module doc comment).
          result = { status: 501, body: { error: 'no RPC handler registered' } }
        } else {
          try {
            const handled = await onRequest({
              fromPubKey,
              method: msg.method,
              path: msg.path,
              headers: msg.headers,
              body: msg.body,
            })
            result = handled && typeof handled === 'object' ? handled : {}
          } catch (err) {
            // onRequest() throwing/rejecting must never become an
            // unhandled rejection or crash the dispatch loop -- turn it
            // into a clean error response instead.
            log('mesh-rpc:handler-threw', { from: fromPubKey, requestId, error: err?.message || String(err) })
            result = { status: 500, body: { error: err?.message || String(err) } }
          }
        }

        const status = typeof result.status === 'number' ? result.status : 200
        const headers = result.headers && typeof result.headers === 'object' ? result.headers : {}
        const body = 'body' in result ? result.body : undefined

        try {
          await ctx.sendTo(fromPubKey, envelopeType, { kind: 'rpc-response', requestId, status, headers, body })
        } catch (err) {
          log('mesh-rpc:response-send-failed', { to: fromPubKey, requestId, error: err?.message || String(err) })
        }
      }

      // -----------------------------------------------------------------
      // Calling side -- this peer awaiting a response to its own request.
      // -----------------------------------------------------------------

      /** @param {string} fromPubKey @param {object} msg */
      function handleResponse(fromPubKey, msg) {
        const pending = pendingRequests.get(msg.requestId)
        if (!pending) return // no longer waiting (already timed out, or not ours) -- ignore
        pendingRequests.delete(msg.requestId)
        clearTimeout(pending.timer)
        pending.resolve({ status: msg.status, headers: msg.headers || {}, body: msg.body })
      }

      /**
       * Send an RPC request to `podId` and await its response.
       * @param {string} podId
       * @param {{method?: string, path?: string, headers?: object, body?: *}} [req]
       * @returns {Promise<{status: number, headers: object, body: *}>}
       *   Rejects if no matching response arrives within `requestTimeoutMs`,
       *   or if `ctx.sendTo()` itself fails (e.g. the peer is unreachable).
       */
      async function request(podId, { method = 'GET', path = '/', headers = {}, body } = {}) {
        const requestId = nextRequestId()

        const promise = new Promise((resolve, reject) => {
          const timer = setTimeout(() => {
            pendingRequests.delete(requestId)
            reject(new Error(`mesh-rpc: request ${method} ${path} to ${podId} timed out after ${requestTimeoutMs}ms`))
          }, requestTimeoutMs)
          pendingRequests.set(requestId, { resolve, reject, timer })
        })

        try {
          await ctx.sendTo(podId, envelopeType, { kind: 'rpc-request', requestId, method, path, headers, body })
        } catch (err) {
          const pending = pendingRequests.get(requestId)
          if (pending) {
            clearTimeout(pending.timer)
            pendingRequests.delete(requestId)
          }
          throw err
        }

        return promise
      }

      const api = { request }

      return {
        api,
        teardown() {
          unsubscribe()
          for (const p of pendingRequests.values()) {
            clearTimeout(p.timer)
            p.reject(new Error('mesh-rpc: service torn down while a request was still in flight'))
          }
          pendingRequests.clear()
        },
      }
    },
  }
}

export { DEFAULT_ENVELOPE_TYPE, DEFAULT_REQUEST_TIMEOUT_MS }
