// cloudflare.config.ts — isolate-pod-host spike (issue #185 WP2)
//
// Generated by `cf migrate` (cf 1.0.0-beta.9) from this spike's previous
// config format, then hand-edited to resolve the two `[required]`
// follow-ups it flagged (see README.md's "cf migration history" note for
// the exact split between generated and hand-written parts, and the exact
// `cf migrate` invocation used):
//   - durable_objects.bindings.0: filled in `exports.durableObject({ storage:
//     "sqlite" })` for PodObject — cf migrate could see the binding but not
//     invent the class's own export declaration.
//   - migrations: the old `[[migrations]] new_sqlite_classes` config has no
//     cf equivalent; a class's storage engine is just part of its `exports`
//     entry now (new classes default to SQLite-shaped config, no migration
//     history to track).
import { bindings, defineConfig, exports } from "cf/config";

export default defineConfig({
	worker: {
		name: "browsermesh-isolate-pod-host-spike",
		compatibilityDate: "2025-01-01",
		compatibilityFlags: [
			"nodejs_compat",
		],
		entrypoint: "src/worker.mjs",
		env: {
			// `cf dev` (beta) does not forward implementation args to a detected
			// framework dev command ("npx vite"), so there is no CLI var-override
			// flag available here the way there used to be (see README.md's
			// "cf migration history" note). This file is a plain TS module
			// re-evaluated on every `cf dev` / `cf build` invocation, so reading
			// `process.env` here is the straightforward replacement — the test
			// harness sets RELAY_URL/SIGNALING_URL in the child process env
			// before spawning `cf dev` to point the Worker at its per-run
			// ephemeral ports.
			RELAY_URL: bindings.text(process.env.RELAY_URL ?? "ws://localhost:8788"),
			SIGNALING_URL: bindings.text(process.env.SIGNALING_URL ?? "ws://localhost:8787"),
			DISCOVERY_CHANNEL: bindings.text("pod-discovery"),
			POD: bindings.durableObject({
				worker: "browsermesh-isolate-pod-host-spike",
				exportName: "PodObject",
			}),
		},
		// One Durable Object instance per hosted pod (idFromName(podName)).
		// `storage: "sqlite"` is the direct equivalent of the old config's
		// `[[migrations]] new_sqlite_classes = ["PodObject"]` — PodObject is a
		// fresh class with no prior migration history, and SQLite-backed
		// storage is what ctx.storage.setAlarm() / ctx.storage.get/put use
		// under the hood for new Durable Object classes.
		exports: {
			PodObject: exports.durableObject({ storage: "sqlite" }),
		},
	},
});
